const SHA='0a097be1d95069f6121326e05985fc1418e9189f';
const RAW=`https://raw.githubusercontent.com/jaredrhod/barehands/${SHA}/`;
const TREE=`https://api.github.com/repos/jaredrhod/barehands/git/trees/${SHA}?recursive=1`;
let treeCache=null,treeT=0;
async function repoTree(){if(treeCache&&Date.now()-treeT<300000)return treeCache;const r=await fetch(TREE,{headers:{'User-Agent':'aelia-natural-control','Accept':'application/vnd.github+json'}});if(!r.ok)throw new Error('GitHub tree '+r.status);const j=await r.json();treeCache=j.tree||[];treeT=Date.now();return treeCache;}
function sendJson(res,obj,code=200){res.status(code);res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.send(JSON.stringify(obj));}
function safeRel(s){s=String(s||'').replace(/\\/g,'/').replace(/^\/+/, '');if(!s||s.includes('..')||s.includes('\0'))return null;return s;}
function addDir(root,parts){let d=root;for(const p of parts){let n=d.dirs.find(x=>x.name===p);if(!n){n={name:p,notes:[],dirs:[]};d.dirs.push(n);}d=n;}return d;}
function addMediaDir(root,parts){let d=root;for(const p of parts){let n=d.dirs.find(x=>x.name===p);if(!n){n={name:p,items:[],dirs:[]};d.dirs.push(n);}d=n;}return d;}
async function notesTree(){const all=await repoTree(),root={name:'Notes',notes:[],dirs:[]};for(const e of all){if(e.type!=='blob'||!e.path.startsWith('sample-notes/')||!e.path.endsWith('.md')||e.path.endsWith('/CLAUDE.md'))continue;const rel=e.path.slice('sample-notes/'.length),parts=rel.split('/'),file=parts.pop(),d=addDir(root,parts);d.notes.push({title:file.replace(/\.md$/,''),file:'0/'+rel});}return root;}
async function propsTree(){const all=await repoTree(),root={name:'Props',items:[],dirs:[]},ok=/\.(png|jpe?g|webp|gif|webm|glb|gltf)$/i;for(const e of all){if(e.type!=='blob'||!e.path.startsWith('media/'))continue;const rel=e.path.slice('media/'.length);if(!ok.test(rel))continue;const parts=rel.split('/'),file=parts.pop(),d=addMediaDir(root,parts);d.items.push(parts.length?parts.concat(file).join('/'):file);}return root;}
module.exports=async function(req,res){const u=new URL(req.url,'https://aelia.local'),route=u.searchParams.get('route')||'';try{if(route==='config')return sendJson(res,{name:'Assistant',orbs:[{title:'Notes',kind:'notes'},{title:'Props',kind:'media'}]});if(route==='tree')return sendJson(res,await notesTree());if(route==='props')return sendJson(res,await propsTree());if(route==='orb')return sendJson(res,{state:'idle',mood:'green',wave:null});if(route==='state'){if(req.method==='POST')return sendJson(res,[]);return sendJson(res,{});}if(route==='cmd'){res.status(204).end();return;}if(route==='note'){const f=safeRel(u.searchParams.get('f'));if(!f)return res.status(404).end();const [idx,...rest]=f.split('/');if(idx!=='0'||!rest.length)return res.status(404).end();const rel=safeRel(rest.join('/'));if(!rel||!rel.endsWith('.md'))return res.status(404).end();const r=await fetch(RAW+'sample-notes/'+rel,{headers:{'User-Agent':'aelia-natural-control'}});if(!r.ok)return res.status(404).end();res.setHeader('Content-Type','text/plain; charset=utf-8');res.setHeader('Cache-Control','no-store');res.status(200).send(await r.text());return;}res.status(404).end();}catch(e){sendJson(res,{error:String(e.message||e)},500);}};
